import React from 'react'; import { Link } from 'react-router-dom'; import SEO from '../components/SEO'; import Section from '../components/Section'; import BookingSection from '../components/BookingSection'; import { posts,faqs } from '../data/siteData'; import { site } from '../data/siteConfig'; import { useLanguage } from '../context/LanguageContext';
const slides=[
 {image:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=2200&q=84',eyebrow:'ZUHD TOURS',title1:'Discover Dubai',title2:'Your Way',text:'Dubai City Tours • Desert Safaris • Private Experiences'},
 {image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=84',eyebrow:'DESERT SAFARI',title1:'Into The Golden',title2:'Desert',text:'Dune adventures, desert camps and memorable UAE experiences'},
 {image:'https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=2200&q=84',eyebrow:'DUBAI & ABU DHABI',title1:'See The UAE',title2:'With Zuhd',text:'Guided city tours, private sightseeing and flexible transport'},
 {image:'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=2200&q=84',eyebrow:'PRIVATE EXPERIENCES',title1:'Travel In',title2:'Comfort',text:'Private tours, guides, SUVs, buses and attraction tickets'}];
const features=[['♢','Local Travel Team','Dubai and UAE tour planning'],['◌','Flexible Services','Private tours, guides and transport'],['◇','Easy Booking','Contact Zuhd Tours for current availability'],['♧','Tailor-Made Tours','Build a trip around your schedule'],['♢','One Contact','Tours, tickets and transport together']];
const destinations=[['Burj Khalifa','The World’s Tallest Building','https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=88'],['Dubai Marina','Luxury & Lifestyle','https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=1200&q=88'],['Palm Jumeirah','Iconic Island','https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=88'],['Dubai Frame','A New Lens on Dubai','https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=1200&q=88'],['Jumeirah Beach','Sun, Sand & Sea','https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=88'],['Old Dubai','Heritage & Culture','https://images.unsplash.com/photo-1726796064162-3aca7cbe3d2f?auto=format&fit=crop&w=1200&q=88'],['Dubai Creek','Tradition & Charm','https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=1200&q=88']];
const popular=[['Desert Safari','Adventure • Desert Experience','https://images.unsplash.com/photo-1717031578847-6b7fd6a94724?auto=format&fit=crop&w=1600&q=88','AED 129','/tours/desert-safari-dubai'],['Abu Dhabi City Tour','Guided sightseeing • UAE Capital','https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=1600&q=88','AED 59','/tours/abu-dhabi-city-tour'],['Dubai City Tour','Heritage • Landmarks • Creek','https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=88','AED 119','/tours/dubai-city-tour'],['Global Village Dubai','Tickets • Culture • Entertainment','https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=1600&q=88','AED 75','/tours/global-village-dubai']];
export default function Home(){const {t,tx}=useLanguage();const [slide,setSlide]=React.useState(0);React.useEffect(()=>{const id=setInterval(()=>setSlide(v=>(v+1)%slides.length),6500);return()=>clearInterval(id)},[]);return <>
<SEO title="Dubai Tours, Desert Safari & Abu Dhabi City Tours | Zuhd Tours" description="Zuhd Tours offers Dubai city tours, Abu Dhabi city tours, desert safari, private tours, dhow cruise, transport, tour guides and attraction tickets in the UAE." path="/" schema={[{'@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:tx(q),acceptedAnswer:{'@type':'Answer',text:tx(a)}}))}]} />
<section className="hero hero-slider" aria-label="Zuhd Tours featured experiences">{slides.map((s,i)=><div key={s.image} className={`hero-slide ${i===slide?'active':''}`} style={{backgroundImage:`url("${s.image}")`}} aria-hidden={i!==slide}/>) }<div className="hero-shade"/><div className="container hero-content"><div className="eyebrow">{slide===0?t.heroEyebrow:tx(slides[slide].eyebrow)}</div><h1>{slide===0?t.heroTitle1:tx(slides[slide].title1)} <span>{slide===0?t.heroTitle2:tx(slides[slide].title2)}</span></h1><p>{slide===0?t.heroSubtitle:tx(slides[slide].text)}</p><div className="actions"><Link className="btn btn-primary" to="/services">{t.explore} <span>→</span></Link><a className="btn btn-ghost" href={site.whatsapp} target="_blank" rel="noreferrer">◉ {t.whatsapp}</a></div></div><div className="hero-contact"><span>◌</span><b>{tx('Direct Booking Support')}</b><small>{tx('Speak with the Zuhd Tours team')}</small><span>◇</span><b>{tx('Flexible Travel Services')}</b><small>{tx('Tours, transport & tickets')}</small></div><div className="hero-dots">{slides.map((s,i)=><button key={s.eyebrow} className={i===slide?'active':''} onClick={()=>setSlide(i)} aria-label={`Show slide ${i+1}`}/>)}</div></section>
<div className="quick-services"><div className="container quick-grid">{[['🏜️','Desert Safari','Feel the adventure','/desert-safari-dubai-tours'],['🏙️',t.dubaiCity,'Explore iconic Dubai','/tours/dubai-city-tour'],['🇦🇪',t.abuDhabi,'Discover the capital','/tours/abu-dhabi-city-tour'],['🚙',t.transport,'SUVs, cars & buses','/transport-services'],['⛵',t.dhow,'Sail the Arabian Gulf','/tours/private-dhow-cruise-dubai']].map(([ic,ttl,s,p])=><Link to={p} key={ttl}><span className="quick-icon">{ic}</span><b>{ttl}</b><small>{tx(s)}</small></Link>)}</div></div>
<Section eyebrow={tx('OUR TOURS')} title={t.popular}><div className="section-head"><p className="lead">{t.featuredLead}</p><Link to="/desert-safari-dubai-tours" className="view-all">{t.viewAll} →</Link></div><div className="home-tour-grid">{popular.map(([n,m,img,price,path])=><article className="home-tour-card" key={n}><Link to={path} className="card-image"><img src={img} alt={`${tx(n)} — Zuhd Tours`} loading="lazy" decoding="async"/><span className="duration">Zuhd Tours</span></Link><div className="home-tour-body"><Link to={path}><h3>{tx(n)}</h3></Link><p>{tx(m)}</p><div className="tour-card-bottom"><b>{tx('From')} <strong>{price}</strong></b><Link className="round-arrow" to={path}>→</Link></div></div></article>)}</div></Section>
<section className="destination-band"><div className="container"><div className="section-head light-head"><div><div className="eyebrow">{tx('TOP DESTINATIONS')}</div><h2>{tx('Explore Dubai’s Iconic Places')}</h2><p>{tx('Iconic landmarks, breathtaking views and unforgettable moments.')}</p></div><Link to="/dubai-top-city-tour-landmarks">{tx('View All Destinations')} →</Link></div><div className="destination-strip">{destinations.map(([n,s,img])=><Link to="/dubai-top-city-tour-landmarks" key={n}><img src={img} alt={`${n} in Dubai`} loading="lazy" decoding="async"/><div><b>{tx(n)}</b><small>{tx(s)}</small></div><span>→</span></Link>)}</div></div></section>
<Section eyebrow={tx('WHY CHOOSE ZUHD TOURS')} title={tx('Travel With Confidence')}><div className="feature-strip">{features.map(([ic,ttl,d])=><div className="feature-inline" key={ttl}><span>{ic}</span><div><b>{tx(ttl)}</b><small>{tx(d)}</small></div></div>)}</div></Section>
<Section eyebrow={tx('ZUHD TOURS SERVICES')} title={tx('Everything You Need for Your UAE Trip')} light><div className="feature-strip">{[['01','City Tours','Dubai and Abu Dhabi sightseeing with flexible routes.'],['02','Desert & Cruise','Desert safari and dhow cruise experiences.'],['03','Private & Transport','Private tours, guides, SUVs, cars and buses.'],['04','Parks Tickets','Attraction and park ticket arrangements across Dubai.']].map(([n,a,b])=><div className="feature-inline" key={n}><span>{n}</span><div><b>{tx(a)}</b><small>{tx(b)}</small></div></div>)}</div></Section>
<Section eyebrow={tx('TRAVEL NOTES')} title={tx('Dubai Travel Guides')}><div className="post-grid">{posts.slice(0,6).map(p=><article className="post-card" key={p.slug}><img src={p.image} alt={tx(p.title)} loading="lazy" decoding="async"/><div><span>{tx(p.category)}</span><h3>{tx(p.title)}</h3><p>{tx(p.excerpt)}</p><Link to={`/blog/${p.slug}`}>{tx('Read guide')} →</Link></div></article>)}</div></Section>
<Section eyebrow={tx('CUSTOMER REVIEWS')} title={tx('What Guests Say About Zuhd Tours')} light><div className="reviews-showcase"><div className="review-summary"><div className="review-brand"><span className="review-g">G</span><div><b>{tx('Customer Reviews')}</b><small>{tx('Zuhd Tours website rating snapshot')}</small></div></div><div className="review-score-row"><strong>4.2</strong><div><div className="review-stars" aria-label="4.2 out of 5 stars">★★★★★</div><b>{tx('Based on 3 reviews shown on the Zuhd Tours website')}</b></div></div><div className="review-total-bar"><i style={{width:'84%'}}/></div><div className="review-total-line"><span>{tx('Overall customer rating')}</span><strong>4.2 / 5</strong></div><p className="review-source">{tx('A quick snapshot of the customer rating currently displayed by Zuhd Tours.')}</p></div><div className="review-highlights"><div className="review-highlights-head"><div><span className="eyebrow dark">{tx('RATING HIGHLIGHTS')}</span><h3>{tx('Feedback at a glance')}</h3></div><span className="review-count">3 {tx('reviews')}</span></div><div className="review-highlight-grid">{[['Location','4.67','Excellent location score'],['Services','4.67','Strong service score'],['Amenities','4.67','Strong amenities score'],['Quality','3.67','Quality score'],['Price','3.33','Value score']].map(([label,value,desc])=><div className="review-highlight" key={label}><div className="highlight-top"><span>{tx(label)}</span><strong>{value}<small>/5</small></strong></div><div className="review-bar"><i style={{width:`${(Number(value)/5)*100}%`}}/></div><p>{tx(desc)}</p></div>)}</div><div className="review-footnote"><span>✓</span><p>{tx('The rating and category scores are taken from the current Zuhd Tours website; no customer names or review text are invented here.')}</p></div></div></div></Section>
<Section eyebrow={tx('FAQ')} title={tx('Before You Book')}><div className="faq">{faqs.map(([q,a])=><details key={q}><summary>{tx(q)}<span>+</span></summary><p>{tx(a)}</p></details>)}</div></Section><BookingSection/></>}
