import React from 'react';
import SEO from '../components/SEO';
import Section from '../components/Section';
import BookingSection from '../components/BookingSection';
import { combos } from '../data/siteData';
import { site } from '../data/siteConfig';
import { useLanguage } from '../context/LanguageContext';

const pages={
  about:{title:'About Zuhd Tours',description:'Discover Zuhd Tours, a Dubai travel company offering city tours, desert safari experiences, private sightseeing, cruises, transport and attraction tickets.',path:'/about'},
  contact:{title:'Contact Zuhd Tours',description:'Talk with Zuhd Tours about desert safaris, city tours, airport transfers, private experiences and attraction tickets.',path:'/contact'},
  transfer:{title:'Dubai Airport Transfer',description:'Private airport pickup and drop-off in Dubai with comfortable vehicles, clear coordination and direct WhatsApp booking.',path:'/dubai-airport-transfer'},
  landmarks:{title:'Top Dubai City Tour Landmarks',description:'Explore Dubai landmarks including Burj Khalifa, Dubai Marina, Palm Jumeirah, Old Dubai, Dubai Creek and Jumeirah.',path:'/dubai-top-city-tour-landmarks'},
  combo:{title:'Dubai Combo Tours & Packages',description:'Combine Dubai desert safari and city sightseeing with flexible multi-day Dubai tour packages.',path:'/combo-tours-dubai'}
};
const landmarks=[['Burj Khalifa','Dubai’s iconic skyline landmark and observation experience.'],['Dubai Marina','Waterfront towers, promenades, dining and boat experiences.'],['Palm Jumeirah','Palm-shaped island with beaches, resorts and Atlantis views.'],['Old Dubai','Historic neighbourhoods, souks and creek-side culture.'],['Dubai Creek','Traditional abra rides and the heart of old trading Dubai.'],['Jumeirah','Beaches, villas and views toward Burj Al Arab.'],['Downtown Dubai','Modern shopping, dining and skyline attractions.']];
const transferFeatures=[['Meet & greet','A clear pickup plan shared before your trip.'],['Flight-friendly timing','Send your flight details so pickup can be coordinated around arrival.'],['Private vehicle','Travel directly to your hotel, residence or chosen destination.'],['Luggage support','Comfortable space for standard travel luggage.'],['Flexible return','Arrange airport drop-off for your departure day.'],['WhatsApp support','Quick confirmation and trip coordination with the Zuhd team.']];

function PageHero({page,tag='ZUHD TOURS'}){const {tx}=useLanguage();return <div className="inner-hero compact-hero"><div className="container"><div className="eyebrow">{tag}</div><h1>{tx(page.title)}</h1><p>{tx(page.description)}</p></div></div>}

function ContactPage(){const {tx}=useLanguage();return <><SEO title={pages.contact.title} description={pages.contact.description} path="/contact" breadcrumbs={[{name:'Home',path:'/'},{name:'Contact',path:'/contact'}]}/><PageHero page={pages.contact} tag="TALK TO ZUHD TOURS"/><section className="contact-modern"><div className="container contact-modern-grid"><div className="contact-copy"><div className="contact-visual"><img src="/assets/ai/ai-dubai-marina.jpg" alt="Dubai Marina travel experience" loading="lazy"/><div><span className="eyebrow">ZUHD TOURS</span><strong>{tx('Plan your UAE experience')}</strong></div></div><span className="eyebrow dark">{tx('CONTACT')}</span><h2>{tx('If you have any questions, feel free to reach out!')}</h2><p>{tx('Tell us your travel date, pickup location, group size and the experience you want. Our team can help you choose the right service and confirm the current details.')}</p><div className="contact-cards"><a href={`tel:${site.phone.replace(/\s/g,'')}`}><b>☎ {tx('Phone')}</b><span>{site.phone}</span></a><a href={`mailto:${site.email}`}><b>✉ {tx('Email')}</b><span>{site.email}</span></a><a href="https://maps.app.goo.gl/X3BNMeBgTHBXM24V7" target="_blank" rel="noreferrer"><b>⌖ {tx('Address')}</b><span>Street 15 House no 11 Al Jaflia Dubai</span></a></div></div><form className="contact-form" onSubmit={e=>e.preventDefault()}><label>{tx('Your Name')}<input placeholder={tx('Your Name')}/></label><label>{tx('Email Address')}<input type="email" placeholder={tx('Email Address')}/></label><label>{tx('Phone Number')}<input placeholder={site.phone}/></label><label>{tx('Subject')}<input placeholder={tx('How can we help?')}/></label><label className="full">{tx('Message')}<textarea rows="6" placeholder={tx('Tell us about your trip...')}/></label><button className="btn btn-primary" type="submit">{tx('Send Enquiry')} →</button></form></div></section><section className="contact-map-section"><div className="container"><div className="section-head"><div><span className="eyebrow dark">{tx('FIND US')}</span><h2>{tx('Hana Center, Al Jaflia')}</h2><p className="lead">{tx('Use the map for directions to the Zuhd Tours area in Al Jaflia, Dubai.')}</p></div><a className="view-all" href="https://maps.app.goo.gl/X3BNMeBgTHBXM24V7" target="_blank" rel="noreferrer">{tx('Open in Google Maps')} →</a></div><div className="map-frame"><iframe title="Zuhd Tours map" src="https://www.google.com/maps?q=Hana%20Center%20Al%20Jafiliya%20Dubai&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></section></>}

function AboutPage(){const {tx}=useLanguage();return <><SEO title={pages.about.title} description={pages.about.description} path="/about" breadcrumbs={[{name:'Home',path:'/'},{name:'About',path:'/about'}]}/><PageHero page={pages.about} tag="LEARN ABOUT US"/><section className="about-intro"><div className="container about-grid"><div className="about-visual"><img src="/assets/gallery/gallery-ai-guests.png" alt="Zuhd Tours desert experience" loading="lazy"/><div><span className="eyebrow">ZUHD TOURS</span><strong>{tx('Dubai & UAE experiences')}</strong></div></div><div><span className="eyebrow dark">{tx('ABOUT ZUHD TOURS')}</span><h2>{tx('Discover the UAE with a local travel team.')}</h2></div><div className="about-copy"><p>{tx('Zuhd Tours is a Dubai travel company focused on practical, memorable experiences across the UAE. Our services bring city sightseeing, desert adventures, cruises, private tours, transport and attraction tickets together in one place.')}</p><p>{tx('Whether you are looking for a first Dubai city tour, an exciting desert safari or a private itinerary, we help you plan around your schedule and travel style.')}</p></div></div></section><section className="about-services"><div className="container"><div className="section-head"><div><span className="eyebrow dark">{tx('OUR SERVICES')}</span><h2>{tx('Travel experiences in one place')}</h2></div></div><div className="about-service-grid">{[['City Tours','Explore Dubai and Abu Dhabi with guided sightseeing and landmark stops.'],['Desert Safari','Enjoy dune adventures, desert scenery and flexible safari arrangements.'],['Dhow Cruise','Experience Dubai waterfront views aboard a traditional dhow.'],['Private Experiences','Build a private itinerary around your group and preferred timing.'],['Transport','Arrange airport transfers and practical travel between destinations.'],['Attractions','Ask about tickets and entry arrangements for popular UAE attractions.']].map(([t,d])=><article key={t}><span>✦</span><h3>{tx(t)}</h3><p>{tx(d)}</p></article>)}</div></div></section><section className="about-cta"><div className="container about-cta-inner"><div><span className="eyebrow">{tx('PLAN YOUR TRIP')}</span><h2>{tx('Ready for an unforgettable tour?')}</h2><p>{tx('Share your dates and preferred experience and we will help you plan the next step.')}</p></div><a className="btn btn-primary" href={site.whatsapp} target="_blank" rel="noreferrer">{tx('Book Tour Now')} →</a></div></section></>}

function TransferPage(){const {tx}=useLanguage();return <><SEO title={pages.transfer.title} description={pages.transfer.description} path="/dubai-airport-transfer" breadcrumbs={[{name:'Home',path:'/'},{name:'Dubai Airport Transfer',path:'/dubai-airport-transfer'}]}/><section className="transfer-hero"><div className="transfer-hero-bg"/><div className="container transfer-hero-content"><div className="eyebrow">AIRPORT TRANSFER • DUBAI</div><h1>{tx('Arrive relaxed. Leave on time.')}</h1><p>{tx('Private Dubai airport pickup and drop-off with a simple booking process and direct support from Zuhd Tours.')}</p><div className="actions"><a className="btn btn-primary" href={site.whatsapp} target="_blank" rel="noreferrer">{tx('Book on WhatsApp')} →</a><a className="btn btn-ghost" href={`tel:${site.phone.replace(/\s/g,'')}`}>{tx('Call us')}</a></div></div></section><section className="transfer-route"><div className="container"><div className="section-head"><div><span className="eyebrow dark">{tx('POPULAR TRANSFERS')}</span><h2>{tx('Airport to your destination')}</h2><p className="lead">{tx('Private transfers can be arranged between Dubai International Airport and your hotel, residence or another Dubai destination.')}</p></div></div><div className="transfer-route-grid">{[['DXB → Dubai Hotel','Private pickup from Dubai International Airport to your hotel.'],['Dubai Hotel → DXB','Departure transfer planned around your flight time.'],['DXB → Abu Dhabi','Private intercity transfer on request.'],['DXB → Cruise / Marina','Direct transfer to Dubai Marina and cruise areas.']].map(([t,d])=><article key={t}><span>01</span><h3>{tx(t)}</h3><p>{tx(d)}</p><a href={site.whatsapp} target="_blank" rel="noreferrer">{tx('Enquire')} →</a></article>)}</div></div></section><section className="transfer-features"><div className="container"><div className="section-head"><div><span className="eyebrow dark">{tx('WHY BOOK WITH ZUHD')}</span><h2>{tx('Simple from pickup to drop-off')}</h2></div></div><div className="transfer-feature-grid">{transferFeatures.map(([t,d])=><article key={t}><span>✓</span><h3>{tx(t)}</h3><p>{tx(d)}</p></article>)}</div></div></section><section className="transfer-book"><div className="container transfer-book-inner"><div><span className="eyebrow">{tx('READY WHEN YOU ARE')}</span><h2>{tx('Send your flight details and let’s arrange the transfer.')}</h2><p>{tx('For a quick quote, send your arrival or departure date, flight number, passenger count and destination on WhatsApp.')}</p></div><a className="btn btn-primary" href={site.whatsapp} target="_blank" rel="noreferrer">{tx('Get a Quote')} →</a></div></section></>}

export default function SimplePage({kind}){const {tx}=useLanguage();const page=pages[kind];if(kind==='contact')return <ContactPage/>;if(kind==='about')return <AboutPage/>;if(kind==='transfer')return <TransferPage/>;return <><SEO title={page.title} description={page.description} path={page.path} breadcrumbs={[{name:'Home',path:'/'},{name:page.title,path:page.path}]}/><PageHero page={page}/>{kind==='combo'?<Section title={tx('Choose a package')}><div className="combo-grid">{combos.map(c=><div className="combo" key={c.title}><span className="badge">{tx('PACKAGE')}</span><h3>{tx(c.title)}</h3><div className="days">{tx(c.days)}</div><div><del>{c.old}</del> <strong>{tx(c.price)}</strong></div>{c.save&&<p>{tx('Save')} {c.save}</p>}<ul>{c.items.map(i=><li key={i}>✓ {tx(i)}</li>)}</ul><a href={site.whatsapp}>{tx('Ask about this package')}</a></div>)}</div></Section>:<Section title={tx('Dubai Highlights')}><div className="landmark-grid">{landmarks.map(([n,d])=><div className="landmark" key={n}><div className="landmark-icon">◆</div><h3>{tx(n)}</h3><p>{tx(d)}</p></div>)}</div></Section>}<BookingSection/></>}
